project:
  type: website

website:
  title: "Hassaan's Qazi Portfolio"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


