---
title: "About"
---

Hello! My name is Hassaan Ali Qazi, and I am currently a Master’s Student at Europa-Universität Viadrina, pursuing a Master's in International Business Administration. My focus areas include Marketing Strategy, Content Marketing, and Customer Relationship Management (CRM). I hold a Bachelor of Business Administration from Shaheed Zulfikar Ali Bhutto Institute of Science and Technology, where I developed a strong foundation in marketing automation tools and analytics.

My professional journey spans roles in digital marketing, content strategy, and client relationship management. At Zameen.com, I served as an Account Manager in Sales, managing over 50 client accounts and significantly increasing client retention and lead generation. I also gained experience in social media planning and SEO optimization during my tenure at Pakistan Digital Awards, where I collaborated on strategies that boosted brand visibility and engagement.

As a Marketing & Sales Intern at Habib Oil Mills, I led comprehensive content marketing strategies and conducted market analysis to identify growth opportunities. My experience also includes a Digital Marketing Apprenticeship at Rock Development Solutions, where I specialized in crafting targeted content strategies and utilizing analytics tools to enhance campaign effectiveness.

I am passionate about leveraging data-driven insights to optimize marketing campaigns and improve customer experiences. You can find more information about my projects and academic publications on my Publications & Projects page. For inquiries, please feel free to contact me.
